name: "Write Data"
 
on:
  schedule:
    - cron: "*/5 * * * *"
 
jobs:
  run-updater:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: REST API with curl
      run: |
        curl "https://raw.githubusercontent.com/olbat/ut1-blacklists/master/blacklists/audio-video/domains" -o main/db.txt
