name: "Data Updater"
 
on:
  schedule:
    - cron: "*/1 * * * *"
jobs: 
  test-run:
   runs-on:
     - ubuntu-latest
   steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: Modify value
      run: |
       curl -N "https://raw.githubusercontent.com/olbat/ut1-blacklists/master/blacklists/audio-video/domains" -o db.txt
       echo 'Add value2' >> testfile.txt
       echo "Commands run successfully"
  
    - name: Commit files
      run: |
       git config --local user.email "achuet414@gmail.com"
       git config --local user.name "GitHub Action test"
       git add testfile.txt
       git commit -m "Add changes"
    - name: Push changes
      uses: ad-m/github-push-action@master
      
