name: "Data Updater"
 
on:
  schedule:
    - cron: "*/1 * * * *"
	
jobs: 
  test-run:
   runs-on:
     - ubuntu-latest
   steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: Modify value
      run: |
       echo 'Add value2' >> testfile.txt
  
    - name: Commit files
      run: |
       git config --local user.email "test@github.com"
       git config --local user.name "GitHub Action test"
       git add ./output
       git commit -m "Add changes"
    - name: Push changes
      uses: ad-m/github-push-action@master
      
